version: '3.8'

services:
  task-api:
    build: C:/Users/james/IdeaProjects/taskAPI
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/housetrackDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=housetrack
    networks:
      - app-network

  login-api:
    build: C:/Users/james/IdeaProjects/housetrack-loginAPI
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/housetrackDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=housetrack
    networks:
      - app-network

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=housetrackDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=housetrack
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
